import { StyleSheet, Text, View } from "react-native";
import { useAppData } from "../../src/data/AppDataContext";
import { canConfirmPreviousWeek, goalForWeek } from "../../src/domain/medals";
import { entriesInWeek, formatMl, sumMl, weekKey } from "../../src/domain/stats";
import { Button, Card, Choice, Field, Screen, Title } from "../../src/ui/components";
import { colors } from "../../src/ui/theme";
import { useState } from "react";
export default function Goals() { const { data, settings, confirmWeek } = useAppData(); const [goal, setGoal] = useState(String(data.settings.weeklyGoalMl)); const reducing = data.settings.objective === "reduce"; const week = entriesInWeek(data.entries); const current = sumMl(week); const prior = new Date(); prior.setDate(prior.getDate() - 7); const priorKey = weekKey(prior); const snapshot = goalForWeek(data, priorKey); const confirmed = data.settings.confirmedWeeks.includes(priorKey); const setObjective = (objective: "track" | "reduce") => void settings({ objective }); const saveGoal = () => { const amount = Number(goal); if (Number.isInteger(amount) && amount >= 100 && amount <= 30000) void settings({ weeklyGoalMl: amount }); };
  const medals = [{ title: "Meu começo", detail: "Escolheu conhecer seus hábitos", unlocked: data.entries.length > 0 }, { title: "Primeiro panorama", detail: "Sete dias desde o começo", unlocked: Date.now() - data.settings.onboardedAt >= 7 * 86400000 }, ...(reducing ? [{ title: "No meu ritmo", detail: "Definiu uma meta pessoal", unlocked: data.settings.weeklyGoalMl > 0 }, { title: "Semana na meta", detail: "Conferiu uma semana encerrada dentro da meta", unlocked: data.settings.achievedWeeks.length > 0 }] : [])];
  return <Screen><Title>Meu objetivo</Title><Text style={styles.copy}>Seu jeito de usar o RefriLog pode mudar a qualquer momento.</Text><Card><Text style={styles.eyebrow}>EU QUERO</Text><Choice active={!reducing} onPress={() => setObjective("track")} title="Só registrar" detail="Acompanhar sem teto, alertas ou cobrança de redução." /><Choice active={reducing} onPress={() => setObjective("reduce")} title="Reduzir no meu ritmo" detail="Usar uma meta semanal voluntária e ajustável." /><Text style={styles.small}>Seus registros continuam aqui quando você troca de objetivo.</Text></Card>{reducing ? <Card><Text style={styles.section}>Meta semanal</Text><Text style={styles.copy}>Uma referência escolhida por você, não uma obrigação.</Text><Field label="Meta em ml" value={goal} onChangeText={setGoal} keyboardType="number-pad" /><Button secondary onPress={saveGoal}>Salvar meta</Button><Text style={styles.progress}>Esta semana: {formatMl(current)} / {formatMl(data.settings.weeklyGoalMl)}</Text>{canConfirmPreviousWeek(data) && snapshot?.objective === "reduce" ? <View style={styles.review}><Text style={styles.section}>Semana passada: {formatMl(sumMl(entriesInWeek(data.entries, prior)))}</Text><Text style={styles.copy}>Confira se registrou tudo antes de avaliar a meta de {formatMl(snapshot.goalMl ?? 0)}.</Text><Button disabled={confirmed} onPress={() => void confirmWeek()}>{confirmed ? "Semana conferida" : "Conferi meus registros"}</Button></View> : null}</Card> : <Card><Text style={styles.section}>Só observar já é um objetivo</Text><Text style={styles.copy}>Veja seus padrões e marcas favoritas. Aqui não há teto ou contagem de dias sem refri.</Text></Card>}<View style={styles.medalHeader}><Text style={styles.section}>Conquistas</Text></View>{medals.map((medal) => <Card key={medal.title}><View style={styles.medal}><Text style={styles.medalIcon}>{medal.unlocked ? "🏅" : "☆"}</Text><View style={styles.flex}><Text style={styles.section}>{medal.title}</Text><Text style={styles.copy}>{medal.detail}</Text></View></View></Card>)}<Text style={styles.small}>Conquistas celebram sua escolha de acompanhar, nunca a quantidade bebida.</Text></Screen>; }
const styles = StyleSheet.create({ copy: { color: colors.muted, fontSize: 14, lineHeight: 20 }, eyebrow: { color: colors.blueDark, fontSize: 11, fontWeight: "800", letterSpacing: 1 }, small: { color: colors.muted, fontSize: 12, lineHeight: 17 }, section: { color: colors.ink, fontSize: 16, fontWeight: "800" }, progress: { color: colors.ink, fontWeight: "800", fontSize: 15 }, review: { gap: 8, backgroundColor: colors.blueSoft, borderRadius: 16, padding: 13, marginTop: 4 }, medalHeader: { marginTop: 5 }, medal: { flexDirection: "row", gap: 12, alignItems: "center" }, medalIcon: { fontSize: 27 }, flex: { flex: 1 } });
