import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useAppData } from "../../src/data/AppDataContext";
import { entriesInWeek, entriesToday, formatBRL, formatMl } from "../../src/domain/stats";
import type { DrinkEntry } from "../../src/domain/types";
import { DrinkEditor } from "../../src/ui/DrinkEditor";
import { Card, Screen, Segmented, Title } from "../../src/ui/components";
import { colors } from "../../src/ui/theme";
export default function History() { const { data, update, remove } = useAppData(); const [filter, setFilter] = useState("week"); const [editing, setEditing] = useState<DrinkEntry>(); const entries = useMemo(() => (filter === "today" ? entriesToday(data.entries) : filter === "week" ? entriesInWeek(data.entries) : data.entries).sort((a, b) => b.at - a.at), [data.entries, filter]); const groups = entries.reduce<Record<string, DrinkEntry[]>>((all, entry) => { const key = new Date(entry.at).toLocaleDateString("pt-BR", { weekday: "long", day: "numeric", month: "long" }); (all[key] ??= []).push(entry); return all; }, {});
  return <Screen><Title>Histórico</Title><Text style={styles.copy}>Toque num registro para editar ou apagar.</Text><Segmented selected={filter} onChange={setFilter} values={[{ id: "today", label: "Hoje" }, { id: "week", label: "Semana" }, { id: "all", label: "Tudo" }]} />{entries.length === 0 ? <Card><Text style={styles.emptyTitle}>Nada por aqui</Text><Text style={styles.copy}>Quando você registrar uma bebida, ela aparece aqui.</Text></Card> : Object.entries(groups).map(([heading, items]) => <View key={heading} style={styles.group}><Text style={styles.heading}>{heading}</Text><Card>{items.map((entry, index) => <Pressable key={entry.id} accessibilityRole="button" onPress={() => setEditing(entry)} style={[styles.entry, index > 0 && styles.entryBorder]}><View style={styles.icon}><Text>🥤</Text></View><View style={styles.flex}><Text style={styles.drink}>{entry.brand}{entry.variant ? ` · ${entry.variant}` : ""}</Text><Text style={styles.copy}>{new Date(entry.at).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })} · {formatMl(entry.ml)}{entry.cost === undefined ? "" : ` · ${formatBRL(entry.cost)}`}</Text></View></Pressable>)}</Card></View>)}{editing ? <DrinkEditor entry={editing} onClose={() => setEditing(undefined)} onSave={(input) => update({ ...input, id: editing.id })} onDelete={() => remove(editing.id)} /> : null}</Screen>; }
const styles = StyleSheet.create({ copy: { color: colors.muted, fontSize: 14, lineHeight: 20 }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" }, group: { gap: 6 }, heading: { color: colors.ink, fontSize: 14, fontWeight: "800", textTransform: "capitalize" }, entry: { flexDirection: "row", alignItems: "center", gap: 11, paddingVertical: 8 }, entryBorder: { borderTopWidth: 1, borderTopColor: colors.border }, icon: { width: 42, height: 42, borderRadius: 15, justifyContent: "center", alignItems: "center", backgroundColor: colors.blueSoft }, flex: { flex: 1 }, drink: { color: colors.ink, fontSize: 14, fontWeight: "800", marginBottom: 2 } });
