import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { useAppData } from "../../src/data/AppDataContext";
import { entriesInWeek, entriesToday, formatBRL, formatMl, sumCost, sumMl } from "../../src/domain/stats";
import { DrinkEditor } from "../../src/ui/DrinkEditor";
import { Button, Card, Mascot, Screen } from "../../src/ui/components";
import { colors } from "../../src/ui/theme";

export default function Home() { const { data, add } = useAppData(); const router = useRouter(); const [editor, setEditor] = useState(false); const today = entriesToday(data.entries); const week = entriesInWeek(data.entries); const volume = sumMl(week); const costs = week.filter((entry) => entry.cost !== undefined); const recent = [...data.entries].sort((a, b) => b.at - a.at).slice(0, 3); const reducing = data.settings.objective === "reduce";
  return <Screen><View style={styles.header}><View><Text style={styles.eyebrow}>REFRILOG</Text><Text style={styles.date}>{new Date().toLocaleDateString("pt-BR", { weekday: "long", day: "numeric", month: "long" })}</Text></View><Mascot small /></View><Card><Text style={styles.eyebrow}>HOJE VOCÊ REGISTROU</Text><Text style={styles.hero}>{formatMl(sumMl(today))}</Text><Text style={styles.copy}>{today.length ? `${today.length} ${today.length === 1 ? "registro" : "registros"} hoje. Obrigado por anotar!` : "Seu diário começa quando você quiser."}</Text></Card><Button onPress={() => setEditor(true)}>+ Registrar refri</Button>{reducing ? <Card><Text style={styles.eyebrow}>MINHA META DA SEMANA</Text><Text style={styles.progress}>{formatMl(volume)} <Text style={styles.light}>/ {formatMl(data.settings.weeklyGoalMl)}</Text></Text><View style={styles.track}><View style={[styles.bar, { width: `${Math.min(100, volume / data.settings.weeklyGoalMl * 100)}%` }]} /></View><Text style={styles.copy}>{volume <= data.settings.weeklyGoalMl ? "Você está acompanhando seu plano. Continue registrando do seu jeito." : "Sua semana passou da referência escolhida. Você pode rever a meta quando quiser."}</Text></Card> : null}<Card><View style={styles.row}><Text style={styles.section}>Sua semana</Text><Text style={styles.week}>{formatMl(volume)}</Text></View><Text style={styles.copy}>Sem registro significa apenas que você não anotou.</Text><View style={styles.stats}><View><Text style={styles.stat}>{formatBRL(sumCost(week))}</Text><Text style={styles.statCopy}>Gasto informado</Text><Text style={styles.small}>{costs.length} de {week.length} registros têm custo</Text></View><View><Text style={styles.stat}>{new Set(week.map((item) => item.brand)).size}</Text><Text style={styles.statCopy}>Marcas registradas</Text></View></View></Card><Card><View style={styles.row}><Text style={styles.section}>Registros recentes</Text><Pressable onPress={() => router.push("/(tabs)/history")}><Text style={styles.link}>Ver histórico</Text></Pressable></View>{recent.length ? recent.map((entry) => <View key={entry.id} style={styles.recent}><Text style={styles.drink}>{entry.brand}{entry.variant ? ` · ${entry.variant}` : ""}</Text><Text style={styles.small}>{new Date(entry.at).toLocaleDateString("pt-BR")} · {formatMl(entry.ml)}</Text></View>) : <Text style={styles.copy}>Quando você registrar uma bebida, ela aparece aqui.</Text>}</Card><Button secondary onPress={() => router.push("/share")}>Compartilhar meu resumo</Button>{editor ? <DrinkEditor onClose={() => setEditor(false)} onSave={add} /> : null}</Screen>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, eyebrow: { color: colors.blueDark, fontSize: 11, fontWeight: "800", letterSpacing: 1 }, date: { color: colors.ink, fontSize: 16, fontWeight: "700", textTransform: "capitalize", marginTop: 3 }, hero: { color: colors.ink, fontSize: 43, fontWeight: "900", marginTop: 7 }, copy: { color: colors.muted, fontSize: 14, lineHeight: 20 }, progress: { color: colors.ink, fontSize: 21, fontWeight: "800" }, light: { color: colors.muted, fontSize: 15 }, track: { backgroundColor: colors.blueSoft, height: 9, borderRadius: 8, overflow: "hidden", marginVertical: 8 }, bar: { backgroundColor: colors.blue, height: "100%", borderRadius: 8 }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, section: { color: colors.ink, fontSize: 16, fontWeight: "800" }, week: { color: colors.blueDark, fontWeight: "800" }, stats: { flexDirection: "row", justifyContent: "space-between", gap: 15, marginTop: 12 }, stat: { color: colors.ink, fontSize: 18, fontWeight: "800" }, statCopy: { color: colors.muted, fontSize: 12, marginTop: 3 }, small: { color: colors.muted, fontSize: 11, marginTop: 3 }, link: { color: colors.blueDark, fontSize: 13, fontWeight: "800" }, recent: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10, marginTop: 4 }, drink: { color: colors.ink, fontWeight: "700", fontSize: 14 } });
