import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { useAppData } from "../../src/data/AppDataContext";
import { chooseBackup, exportBackup, exportCsv } from "../../src/data/files";
import { Button, Card, Mascot, Screen, Title } from "../../src/ui/components";
import { colors } from "../../src/ui/theme";
export default function Settings() { const { data, replace, clear } = useAppData(); const router = useRouter(); const run = async (action: () => Promise<void>) => { try { await action(); } catch (error) { Alert.alert("Não foi possível concluir", error instanceof Error ? error.message : "Tente novamente."); } }; const restore = async () => { const imported = await chooseBackup(); if (!imported) return; Alert.alert("Substituir dados deste aparelho?", `O backup tem ${imported.entries.length} registros. Seus dados atuais serão substituídos.`, [{ text: "Cancelar", style: "cancel" }, { text: "Restaurar", style: "destructive", onPress: () => void replace(imported) }]); };
  return <Screen><Title>Ajustes</Title><Text style={styles.copy}>Seus dados e escolhas, neste aparelho.</Text><Card><Setting title="Exportar CSV" detail={`${data.entries.length} registros para análise`} onPress={() => void run(() => exportCsv(data))} /><Setting title="Exportar backup" detail="JSON completo para restaurar depois" onPress={() => void run(() => exportBackup(data))} /><Setting title="Importar backup" detail="Valida antes de substituir seus dados" onPress={() => void run(restore)} /><Setting title="Compartilhar resumo" detail="Você escolhe quando e com quem" onPress={() => router.push("/share")} /><Setting danger title="Apagar todos os dados" detail="Remove os registros deste aparelho" onPress={() => Alert.alert("Apagar seus dados?", "Isso remove os registros, metas e confirmações deste aparelho. Não é possível desfazer.", [{ text: "Manter", style: "cancel" }, { text: "Apagar", style: "destructive", onPress: () => void clear() }])} /></Card><View style={styles.brand}><Mascot /><Text style={styles.name}>RefriLog</Text><Text style={styles.copy}>Seu refri, do seu jeito.</Text><Text style={styles.notice}>Os dados ficam neste aparelho e podem ser perdidos sem backup. Não há conta, servidor ou sincronização nesta versão.</Text><Text style={styles.small}>Versão 1.0.0 · Privacidade: seus registros não saem do aparelho sem uma ação explícita de compartilhar ou exportar.</Text></View></Screen>; }
function Setting({ title, detail, onPress, danger }: { title: string; detail: string; onPress: () => void; danger?: boolean }) { return <Pressable accessibilityRole="button" onPress={onPress} style={styles.setting}><Text style={[styles.settingTitle, danger && styles.danger]}>{title}</Text><Text style={styles.copy}>{detail}</Text></Pressable>; }
const styles = StyleSheet.create({ copy: { color: colors.muted, fontSize: 14, lineHeight: 20 }, setting: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border, gap: 3 }, settingTitle: { color: colors.ink, fontWeight: "800", fontSize: 16 }, danger: { color: colors.danger }, brand: { alignItems: "center", gap: 7, paddingVertical: 8 }, name: { color: colors.ink, fontSize: 16, fontWeight: "800" }, notice: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 7 }, small: { color: colors.muted, fontSize: 11, lineHeight: 16, textAlign: "center" } });
