import { useRef, useState } from "react";
import { Alert, Share, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { captureRef } from "react-native-view-shot";
import * as Sharing from "expo-sharing";
import { useAppData } from "../src/data/AppDataContext";
import { entriesInWeek, formatMl, sumMl } from "../src/domain/stats";
import { Button, Mascot, Screen, Title } from "../src/ui/components";
import { colors } from "../src/ui/theme";
export default function SharePreview() { const { data } = useAppData(); const router = useRouter(); const card = useRef<View>(null); const [sending, setSending] = useState(false); const volume = formatMl(sumMl(entriesInWeek(data.entries))); const text = data.settings.objective === "reduce" ? `Meu resumo no RefriLog: ${volume} registrados nesta semana. Minha meta pessoal é ${formatMl(data.settings.weeklyGoalMl)}. No meu ritmo!` : `Meu resumo no RefriLog: ${volume} registrados nesta semana. Conhecendo meus hábitos, do meu jeito.`; const shareImage = async () => { setSending(true); try { const uri = await captureRef(card, { format: "png", quality: 1, result: "tmpfile" }); if (!await Sharing.isAvailableAsync()) throw new Error("O compartilhamento não está disponível neste aparelho."); await Sharing.shareAsync(uri, { mimeType: "image/png", dialogTitle: "Compartilhar cartão RefriLog" }); } catch (error) { if (error instanceof Error && !/cancel/i.test(error.message)) Alert.alert("Não foi possível compartilhar", error.message); } finally { setSending(false); } };
  return <Screen><Title>Seu resumo</Title><Text style={styles.copy}>Confira o cartão antes de decidir compartilhar. Nenhum dado sai do aparelho sem sua ação.</Text><View ref={card} collapsable={false} style={styles.card}><Mascot /><Text style={styles.eyebrow}>MEU REFRILOG</Text><Text style={styles.volume}>{volume}</Text><Text style={styles.cardText}>{data.settings.objective === "reduce" ? `registrados nesta semana · meta pessoal: ${formatMl(data.settings.weeklyGoalMl)}` : "registrados nesta semana"}</Text><Text style={styles.footer}>Seu refri, do seu jeito.</Text></View><Button disabled={sending} onPress={() => void shareImage()}>{sending ? "Preparando cartão..." : "Compartilhar cartão como imagem"}</Button><Button secondary onPress={() => void Share.share({ title: "Meu RefriLog", message: text })}>Compartilhar texto</Button><Button secondary onPress={() => router.back()}>Voltar</Button></Screen>; }
const styles = StyleSheet.create({ copy: { color: colors.muted, fontSize: 14, lineHeight: 20 }, card: { alignItems: "center", backgroundColor: colors.blueSoft, borderRadius: 28, padding: 25, borderWidth: 2, borderColor: colors.blue, gap: 7 }, eyebrow: { color: colors.blueDark, fontSize: 12, fontWeight: "900", letterSpacing: 1.4 }, volume: { color: colors.ink, fontSize: 36, fontWeight: "900" }, cardText: { color: colors.ink, fontSize: 15, textAlign: "center" }, footer: { color: colors.blueDark, fontWeight: "800", fontSize: 13, marginTop: 10 } });
