import { type PropsWithChildren } from "react";
import { Image, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors } from "./theme";

export const mascot = require("../../assets/mascot.jpg");
export function Screen({ children }: PropsWithChildren) { return <SafeAreaView edges={["top", "left", "right"]} style={styles.safeArea}><ScrollView style={styles.scroll} contentContainerStyle={styles.screen} keyboardShouldPersistTaps="handled">{children}</ScrollView></SafeAreaView>; }
export function Card({ children }: PropsWithChildren) { return <View style={styles.card}>{children}</View>; }
export function Title({ children }: PropsWithChildren) { return <Text style={styles.title}>{children}</Text>; }
export function Copy({ children }: PropsWithChildren) { return <Text style={styles.copy}>{children}</Text>; }
export function Button({ children, onPress, secondary = false, disabled = false }: PropsWithChildren<{ onPress: () => void; secondary?: boolean; disabled?: boolean }>) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button, secondary && styles.secondary, disabled && styles.disabled]}><Text style={[styles.buttonText, secondary && styles.secondaryText]}>{children}</Text></Pressable>; }
export function Field({ label, help, ...props }: TextInputProps & { label: string; help?: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor="#94A3B8" style={styles.input} {...props} />{help ? <Text style={styles.help}>{help}</Text> : null}</View>; }
export function Choice({ active, title, detail, onPress }: { active: boolean; title: string; detail: string; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ selected: active }} onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><Text style={styles.choiceTitle}>{title}</Text><Text style={styles.copy}>{detail}</Text></Pressable>; }
export function Dialog({ visible, title, children, onClose }: PropsWithChildren<{ visible: boolean; title: string; onClose: () => void }>) { return <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}><View style={styles.modalBackdrop}><SafeAreaView edges={["bottom", "left", "right"]} style={styles.modal}><View style={styles.modalHeader}><Text style={styles.title}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="Fechar" onPress={onClose}><Text style={styles.close}>Fechar</Text></Pressable></View>{children}</SafeAreaView></View></Modal>; }
export function Mascot({ small = false }: { small?: boolean }) { return <Image source={mascot} accessibilityLabel="Lata, mascote do RefriLog" style={[styles.mascot, small && styles.mascotSmall]} />; }
export function Segmented({ values, selected, onChange }: { values: { id: string; label: string }[]; selected: string; onChange: (id: string) => void }) { return <View style={styles.segment}>{values.map((item) => <Pressable key={item.id} onPress={() => onChange(item.id)} style={[styles.segmentItem, selected === item.id && styles.segmentSelected]}><Text style={[styles.segmentText, selected === item.id && styles.segmentTextSelected]}>{item.label}</Text></Pressable>)}</View>; }
const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background }, scroll: { flex: 1 }, screen: { flexGrow: 1, padding: 20, gap: 14, backgroundColor: colors.background }, card: { backgroundColor: colors.surface, borderRadius: 24, padding: 18, borderWidth: 1, borderColor: colors.border, gap: 8 }, title: { color: colors.ink, fontSize: 25, lineHeight: 31, fontWeight: "800" }, copy: { color: colors.muted, fontSize: 14, lineHeight: 20 }, button: { minHeight: 52, alignItems: "center", justifyContent: "center", borderRadius: 16, backgroundColor: colors.blue, paddingHorizontal: 16 }, buttonText: { color: "white", fontSize: 16, fontWeight: "800" }, secondary: { backgroundColor: colors.blueSoft }, secondaryText: { color: colors.blueDark }, disabled: { opacity: .45 }, field: { gap: 6 }, label: { fontSize: 14, fontWeight: "700", color: colors.ink }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 13, paddingHorizontal: 13, backgroundColor: "white", fontSize: 16, color: colors.ink }, help: { fontSize: 12, color: colors.muted, lineHeight: 17 }, choice: { padding: 17, borderWidth: 1, borderColor: colors.border, borderRadius: 20, gap: 5, backgroundColor: "white" }, choiceActive: { borderColor: colors.blue, borderWidth: 2, backgroundColor: "#F3FAFF" }, choiceTitle: { fontSize: 16, fontWeight: "800", color: colors.ink }, modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(24,48,68,.35)" }, modal: { maxHeight: "92%", backgroundColor: colors.background, borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: 20, paddingTop: 20, gap: 16 }, modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, close: { color: colors.blueDark, fontWeight: "700", fontSize: 15 }, mascot: { width: 130, height: 130, resizeMode: "contain", alignSelf: "center" }, mascotSmall: { width: 58, height: 58, alignSelf: "auto" }, segment: { backgroundColor: colors.blueSoft, flexDirection: "row", padding: 4, borderRadius: 22 }, segmentItem: { flex: 1, minHeight: 38, alignItems: "center", justifyContent: "center", borderRadius: 18 }, segmentSelected: { backgroundColor: "white" }, segmentText: { color: colors.muted, fontWeight: "700" }, segmentTextSelected: { color: colors.ink },
});
