import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { DrinkEntry } from "../domain/types";
import { Button, Dialog, Field, Segmented } from "./components";
import { colors } from "./theme";

const brands = ["Coca-Cola", "Pepsi", "Guaraná Antarctica", "Fanta", "Sprite", "Sukita", "Outra marca"];
const portions = [200, 350, 600, 1000, 2000];
const toDateInput = (value: number) => { const d = new Date(value); return `${String(d.getDate()).padStart(2, "0")}/${String(d.getMonth() + 1).padStart(2, "0")}/${d.getFullYear()} ${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`; };
const parseDateInput = (value: string): number | undefined => { const match = value.match(/^(\d{2})\/(\d{2})\/(\d{4})\s(\d{2}):(\d{2})$/); if (!match) return undefined; const [, day, month, year, hour, minute] = match; const date = new Date(+year, +month - 1, +day, +hour, +minute); return date.getFullYear() === +year && date.getMonth() === +month - 1 && date.getDate() === +day ? date.getTime() : undefined; };
export function DrinkEditor({ entry, onSave, onDelete, onClose }: { entry?: DrinkEntry; onSave: (input: Omit<DrinkEntry, "id">) => Promise<void>; onDelete?: () => Promise<void>; onClose: () => void }) {
  const [brand, setBrand] = useState(entry?.brand ?? "Coca-Cola"); const [customBrand, setCustomBrand] = useState(""); const [variant, setVariant] = useState(entry?.variant ?? ""); const [ml, setMl] = useState(String(entry?.ml ?? 350)); const [cost, setCost] = useState(entry?.cost === undefined ? "" : String(entry.cost).replace(".", ",")); const [at, setAt] = useState(toDateInput(entry?.at ?? Date.now())); const [saving, setSaving] = useState(false);
  useEffect(() => { if (entry && !brands.includes(entry.brand)) { setBrand("Outra marca"); setCustomBrand(entry.brand); } }, [entry]);
  const save = async () => { if (saving) return; const actualBrand = brand === "Outra marca" ? customBrand.trim() : brand; const volume = Number(ml); const price = cost.trim() ? Number(cost.replace(",", ".")) : undefined; const time = parseDateInput(at); if (!actualBrand || !Number.isInteger(volume) || volume < 1 || volume > 10000 || !time || (price !== undefined && (!Number.isFinite(price) || price < 0 || price > 10000))) { Alert.alert("Confira o registro", "Informe marca, quantidade de 1 a 10.000 ml e data/hora no formato DD/MM/AAAA HH:MM. O custo é opcional."); return; } setSaving(true); try { await onSave({ at: time, brand: actualBrand, variant: variant.trim() || undefined, ml: volume, cost: price }); onClose(); } catch { Alert.alert("Não salvamos o registro", "Tente novamente. Seus dados anteriores continuam preservados."); } finally { setSaving(false); } };
  return <Dialog visible title={entry ? "Editar registro" : "Registrar refri"} onClose={onClose}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Text style={styles.intro}>Registre a quantidade que você realmente bebeu.</Text><Text style={styles.label}>Marca</Text><View style={styles.brands}>{brands.map((item) => <Pressable key={item} onPress={() => setBrand(item)} style={[styles.brand, brand === item && styles.brandSelected]}><Text style={[styles.brandText, brand === item && styles.brandTextSelected]}>{item}</Text></Pressable>)}</View>{brand === "Outra marca" ? <Field label="Nome da marca" value={customBrand} onChangeText={setCustomBrand} maxLength={60} placeholder="Qual marca?" /> : null}<Field label="Versão (opcional)" value={variant} onChangeText={setVariant} maxLength={60} placeholder="Zero, original, sabor..." /><Text style={styles.label}>Quanto você bebeu?</Text><View style={styles.portions}>{portions.map((amount) => <Pressable key={amount} onPress={() => setMl(String(amount))} style={[styles.portion, Number(ml) === amount && styles.portionSelected]}><Text style={styles.portionText}>{amount >= 1000 ? `${amount / 1000} L` : `${amount} ml`}</Text></Pressable>)}</View><Field label="Quantidade efetivamente consumida em ml" keyboardType="number-pad" value={ml} onChangeText={setMl} help="Pode ser só um copo, mesmo se a embalagem for maior." /><Field label="Custo atribuído a esta quantidade (opcional)" keyboardType="decimal-pad" value={cost} onChangeText={setCost} placeholder="R$ 0,00" help="Não assumimos o preço de uma garrafa como custo de um copo." /><Field label="Data e hora" value={at} onChangeText={setAt} placeholder="DD/MM/AAAA HH:MM" help="Você pode registrar um consumo anterior." /><Button disabled={saving} onPress={() => void save()}>{saving ? "Salvando..." : entry ? "Salvar alterações" : "Registrar"}</Button>{entry && onDelete ? <Button secondary onPress={() => Alert.alert("Apagar registro?", "Essa ação não pode ser desfeita.", [{ text: "Manter", style: "cancel" }, { text: "Apagar", style: "destructive", onPress: () => void onDelete().then(onClose) }])}>Apagar registro</Button> : null}</ScrollView></Dialog>;
}
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 22 }, intro: { color: colors.muted, fontSize: 14 }, label: { color: colors.ink, fontWeight: "700", fontSize: 14 }, brands: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, brand: { borderWidth: 1, borderColor: colors.border, borderRadius: 18, paddingHorizontal: 12, paddingVertical: 9 }, brandSelected: { borderColor: colors.blue, backgroundColor: colors.blueSoft }, brandText: { fontSize: 13, color: colors.ink }, brandTextSelected: { color: colors.blueDark, fontWeight: "700" }, portions: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, portion: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 10 }, portionSelected: { borderColor: colors.blue, backgroundColor: colors.blueSoft }, portionText: { color: colors.ink, fontWeight: "700", fontSize: 13 } });
